#!/bin/bash
set -euo pipefail

# Generate the Codex adapter from the canonical opencode config and role files.
# Never hand-edit generated .codex/agents/*.toml; edit opencode.json or
# .opencode/agent/*.md and run this script.

ROOT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)
OPENCODE_JSON="$ROOT_DIR/opencode.json"
CODEX_DIR="$ROOT_DIR/.codex"
CODEX_AGENT_DIR="$CODEX_DIR/agents"

for tool in jq awk grep; do
  if ! command -v "$tool" >/dev/null 2>&1; then
    echo "ERROR: sync-codex requires $tool" >&2
    exit 1
  fi
done

# Per-harness models come from factory.yaml (Decision 41; older repos keep theirs
# in factory.config and are still read). Neither defines them in the template
# repo, so CODEX_*_MODEL stay unset and agents inherit the session model, keeping
# committed adapters clean. role_tier() maps role→tier.
# shellcheck source=lib/config.sh
. "$ROOT_DIR/scripts/lib/config.sh"
factory_config_export
# shellcheck source=lib/roles.sh
. "$ROOT_DIR/scripts/lib/roles.sh"

mkdir -p "$CODEX_AGENT_DIR"

cat > "$CODEX_DIR/config.toml" <<'EOF'
# Generated by scripts/sync-codex.sh from opencode.json.
# Codex loads project config only after the repository is trusted.

[agents]
max_threads = 4
max_depth = 1

[mcp_servers.playwright]
command = "npx"
args = ["-y", "@playwright/mcp"]
EOF

AGENTS=$(jq -r '.agent // {} | keys[]' "$OPENCODE_JSON")

for AGENT_NAME in $AGENTS; do
  DESCRIPTION=$(jq -r --arg name "$AGENT_NAME" '.agent[$name].description // ""' "$OPENCODE_JSON")
  EDIT_PERM=$(jq -r --arg name "$AGENT_NAME" '.agent[$name].permission.edit // "ask"' "$OPENCODE_JSON")
  ROLE_FILE="$ROOT_DIR/.opencode/agent/${AGENT_NAME}.md"

  if [ ! -f "$ROLE_FILE" ]; then
    echo "ERROR: canonical role file not found: $ROLE_FILE" >&2
    exit 1
  fi

  if grep -q '"""' "$ROLE_FILE"; then
    echo "ERROR: role body contains TOML multiline delimiter: $ROLE_FILE" >&2
    exit 1
  fi

  BODY=$(awk '
    /^---$/ { frontmatter_delimiters++; next }
    frontmatter_delimiters >= 2 { print }
  ' "$ROLE_FILE")

  SANDBOX_MODE="workspace-write"
  if [ "$EDIT_PERM" = "deny" ]; then
    SANDBOX_MODE="read-only"
  fi

  # Per-agent model: Codex agent files support a top-level `model` key
  # (learn.chatgpt.com/docs/agent-configuration/subagents). The model for this
  # role is its tier's CODEX_<TIER>_MODEL from factory.config (a native Codex id,
  # e.g. gpt-5.6-sol). Unset — the template repo, or a blanked tier — omits the
  # line so the agent inherits the session model.
  TIER=$(role_tier "$AGENT_NAME")
  case "$(resolve_tier "${COST_PROFILE:-standard}" "$TIER")" in
    frontier) CODEX_MODEL="${CODEX_FRONTIER_MODEL:-}" ;;
    economy)  CODEX_MODEL="${CODEX_ECONOMY_MODEL:-}" ;;
    *)        CODEX_MODEL="${CODEX_DEFAULT_MODEL:-}" ;;
  esac
  # Emit only a native Codex id. Empty (unset tier), a cross-provider slug
  # (contains "/"), or an unresolved placeholder (contains "__") would be an
  # invalid model, so omit the line and let the agent inherit the session model.
  MODEL_LINE=""
  case "$CODEX_MODEL" in
    ""|*"/"*|*"__"*) : ;;
    *) printf -v MODEL_LINE 'model = "%s"\n' "$CODEX_MODEL" ;;
  esac

  AGENT_FILE="$CODEX_AGENT_DIR/${AGENT_NAME}.toml"
  cat > "$AGENT_FILE" <<EOF
# Generated by scripts/sync-codex.sh. Do not hand-edit.
name = "${AGENT_NAME}"
description = "${DESCRIPTION}"
${MODEL_LINE}sandbox_mode = "${SANDBOX_MODE}"
developer_instructions = """
${BODY}
"""
EOF

  if [ "$AGENT_NAME" = "implementer" ]; then
    cat >> "$AGENT_FILE" <<'EOF'

[[hooks.PreToolUse]]
matcher = "^(apply_patch|Edit|Write)$"

[[hooks.PreToolUse.hooks]]
type = "command"
command = 'FACTORY_AGENT_ROLE=implementer "$(git rev-parse --show-toplevel)/scripts/hooks/test-edit-denial.sh"'
timeout = 30
statusMessage = "Enforcing implementer test-file boundary"
EOF
  fi

  echo "sync-codex: wrote .codex/agents/${AGENT_NAME}.toml"
done

echo "sync-codex: wrote .codex/config.toml"
echo "sync-codex: done"
