spring:
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        options:
          model: lfm2.5
    mcp:
      client:
        enabled: false
        sse:
          connections:
            polyglot:
              url: http://localhost:9000

vaadin:
  productionMode: true

server:
  port: 8080
